language: generic
os: linux
services: docker
branches:
  only:
  - master
env:
  global:
  - PROJECT_NAME=lpp-buses
  - PROJECT_VERSION=1.0.4
  - DOCKER_USERNAME=bezpov
  - secure: yHiMUm0hRleYQWtrgN1d36LV02YmkFKSRS7mfg6wG6HlYrkCXVsa9qqnAuS4w+xe3yKnOddL7Y8cckMClwsVXbh9iRwMiiyXhnSAyPywEZW+y8QmXA/poyaOCezdRitzaI1BHCcXHgOpPp4qw6Xdvc45eecqSHmyGyFcTBpJr5Py1qZOaPtRcYHIHwLWCdABbmRoaWMBuox9R8dKO82EmnZI6zm7t90t++Fz7+Q9nEEVfWusAC72f/zlRSFSxPOxQsCPCGhRAJdSXMvkGAszP+IsZ74zmr4vUQt9Y8kIpyeW9egZ2zWsnzIOLKf6HBS4fjqKqTfIIz1vr2jxEus3qLEnwOyutkQQW9EGAfCycolkArwQXQgNh1L4lwup17Im4qhf3BFQWvhcux+Ez/Cq1g6lGPa4gcHXMi3dX0oqqDRHOrFL2pO5NoxB/VU7xO5KbJBpbqOM0treBS27WJ3LsKIw2iYszCvxHk+Xw5T2+Q3EcBlWQtEb2beuui6/JG+YeomGASAMBqKVK6RAiQz7wWasJkqqkmmW5qfk6mdjL+QFO0s1CDpXyg9Y/AqocQM5Dk0mdRy0mKj7obj2bfLSDObZzhgNAFFmYituahWfvF0IurmRlGoPjI6SiZGDcx0RW4FhxGjPXAjvBea8MmXugal1zBFK78cZJJZ1LCY1SdA=
  - secure: Sq47XOKptnGc8EnoLhQ41kMNAJxN5o+MVsxainckALxHMUS5duFa465ixkrfYo16nK1IyjpZEXfzFELvst2tfB4lrCDk6lhTRO2fbCTCOifPsRzfmAZGVJftGMRypMnkx5SCImTjKaAF2amqU6kh+NisKoBimwFUW8LgejPbnYZpZNbah++PVnSNIqGiGpqiyBS8c88fRcLLBhtZEJTjypcci+9Beu7fbXqSr98ELpAJXqvi+X37bB+EATCY5kSpR0TOVUiMR06EZIMwPbSGfUT/SyTHFDS9m0mp+jMwvj6ojX6Du9uFNQ5EEZ92Le3NOMSehdfLqE1puzKiIufMobXqbRbj6dK9abM7xIw0NcHxh6rp2K8BSDU66413ojl08+o3nwefcWYx6PAD+FBQ8BbZ+j2AgGAz72UNRViukAvzTrdKKlVhBBsr4GbTUxpGsZe+lJqm1bqsDoLW0kpMmwrEj3XLAqqHX47jpHBDp4smoNBGMdyx51TriZeGJkx9fyw/1IEaI/HHMhDqskeo21MLCS1/qlmVBGI5b0SC+dGy/kqsqi1i/cLv+W1B7eKBIizrp05IFdiFuXZYJuBvNVoxWmgm7f7mZ1e42HOLrhr1FAeSGLPMkcwUZP+hoWW01TwEzEK4ntWsezKbMv/1qy30uyrV5nXVNkowZDN9Rns=
before_install:
- echo "$GOOGLE_INTEGRATION_PASSWORD" | gpg --batch --yes --passphrase-fd 0 ./config/google-travis-service-account.json.gpg
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud auth activate-service-account --key-file ./config/google-travis-service-account.json
- gcloud config set project massive-boulder-263710
- gcloud container clusters get-credentials lpp --zone us-central1-a --project massive-boulder-263710
- gcloud components install kubectl
- kubectl apply -f ./kubernetes/deployment.yaml
